kollus-upload-proxy:
  domain: kollus-upload-proxy.app
  is_dev_mode: true
  use_twig_cache: false
database:
  driver: pdo_mysql
  host: localhost
  dbname: kollus_upload_proxy
  user: kollus_upload_proxy
  password: kollus_upload_proxy
kollus:
  your-service-account-key:
    service_account_key: kollus_service_account_key
    domain: kr.kollus.com
    api_access_token: api_access_token
    channel_callback_url: channel_callback_url
